version: '3.8'

services:
  playwright-filter:
    build: .
    container_name: playwright-filter
    restart: unless-stopped
    ports:
      - '3012:3000'
    environment:
      - NODE_ENV=production
